import type { PoseSet } from './build-clips.js';

/**
 * Cat sprite art, authored as character grids.
 *
 * Legend: `.` transparent, `o` outline, `B` body, `D` shaded body, `L` lit body,
 * `W` white marking, `w` shaded marking, `G` iris, `P` pupil, `S` eye shine,
 * `n` nose, `y` inner ear, `m` mouth.
 *
 * Poses are authored once here and assembled into animation clips in
 * `cat-base.ts`.
 */

/** Sitting, facing the viewer. The resting pose. */
export const FRONT = [
  '..............................',
  '..............................',
  '........oo..........oo........',
  '.......oyBo........oByo.......',
  '......oyyBBo......oBByyo......',
  '......oyBBBooooooooBBByo......',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBGGGGBBBBBBGGGGBBBo....',
  '....oBBBGSPGBBBBBBGSPGBBBo....',
  '....oBBBGGGGBBBBBBGGGGBBBo....',
  '....oBBBBBBBBBnnBBBBBBBBBo....',
  '....oBBBBBBBWWmmWWBBBBBBBo....',
  '.....oBBBBBBWWWWWWBBBBBBo.....',
  '......oBBBBBBWWWWBBBBBBo......',
  '.......oBBBBBBBBBBBBBBo.......',
  '......oLBBBBBWWWWBBBBBLo......',
  '......oBBBBBWWWWWWBBBBBo......',
  '......oBBBBBWWWWWWBBBBBo..oo..',
  '......oBBBBBWWWWWWBBBBBo.oDDo.',
  '......oBBBBBBWWWWBBBBBBooDDo..',
  '......oBBBBBBBBBBBBBBBBoDDo...',
  '.......oBBBBBBBBBBBBBBoDDo....',
  '.......oBBBBBBBBBBBBBBBoo.....',
  '.......oWWWooooooooWWWo.......',
  '.......oWWWo......oWWWo.......',
  '.......oooo........oooo.......',
  '..............................',
  '..............................',
  '..............................',
];

/** Front pose with the eyes closed, used for the idle blink. */
export const FRONT_BLINK = [
  '..............................',
  '..............................',
  '........oo..........oo........',
  '.......oyBo........oByo.......',
  '......oyyBBo......oBByyo......',
  '......oyBBBooooooooBBByo......',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBooooBBBBBBooooBBBo....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBBBBBBnnBBBBBBBBBo....',
  '....oBBBBBBBWWmmWWBBBBBBBo....',
  '.....oBBBBBBWWWWWWBBBBBBo.....',
  '......oBBBBBBWWWWBBBBBBo......',
  '.......oBBBBBBBBBBBBBBo.......',
  '......oLBBBBBWWWWBBBBBLo......',
  '......oBBBBBWWWWWWBBBBBo......',
  '......oBBBBBWWWWWWBBBBBo..oo..',
  '......oBBBBBWWWWWWBBBBBo.oDDo.',
  '......oBBBBBBWWWWBBBBBBooDDo..',
  '......oBBBBBBBBBBBBBBBBoDDo...',
  '.......oBBBBBBBBBBBBBBoDDo....',
  '.......oBBBBBBBBBBBBBBBoo.....',
  '.......oWWWooooooooWWWo.......',
  '.......oWWWo......oWWWo.......',
  '.......oooo........oooo.......',
  '..............................',
  '..............................',
  '..............................',
];

/** Front pose with happy squinted eyes and blushed cheeks, for the heart clip. */
export const FRONT_HAPPY = [
  '..............................',
  '..............................',
  '........oo..........oo........',
  '.......oyBo........oByo.......',
  '......oyyBBo......oBByyo......',
  '......oyBBBooooooooBBByo......',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBooBBBBBBBBooBBBBo....',
  '....oBBBoBBoBBBBBBoBBoBBBo....',
  '....onnBBBBBBBBBBBBBBBBnno....',
  '....onnBBBBBBBnnBBBBBBnnno....',
  '....oBBBBBBBWWmmWWBBBBBBBo....',
  '.....oBBBBBBWWWWWWBBBBBBo.....',
  '......oBBBBBBWWWWBBBBBBo......',
  '.......oBBBBBBBBBBBBBBo.......',
  '......oLBBBBBWWWWBBBBBLo......',
  '......oBBBBBWWWWWWBBBBBo......',
  '......oBBBBBWWWWWWBBBBBo..oo..',
  '......oBBBBBWWWWWWBBBBBo.oDDo.',
  '......oBBBBBBWWWWBBBBBBooDDo..',
  '......oBBBBBBBBBBBBBBBBoDDo...',
  '.......oBBBBBBBBBBBBBBoDDo....',
  '.......oBBBBBBBBBBBBBBBoo.....',
  '.......oWWWooooooooWWWo.......',
  '.......oWWWo......oWWWo.......',
  '.......oooo........oooo.......',
  '..............................',
  '..............................',
  '..............................',
];

/** Side profile facing right, front legs reaching forward. Walk key 1. */
export const SIDE_A = [
  '..............................',
  '..............................',
  '..............................',
  '....................oo...oo...',
  '...................oyBo.oByo..',
  '..................oyyBBooBByo.',
  '.................oyBBBBBBBByo.',
  '.................oLLLLLLLLLLo.',
  '................oBBBBBBBBBBBo.',
  '................oBGGGGBBBBBBo.',
  '................oBGSPGBBBnnBo.',
  '................oBGGGGBBBmmBo.',
  '.................oBBBBBBBWWo..',
  '..........ooooooLLLLLLLLLLo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '...ooDDDDDDBBBBBBBBBBBBBo.....',
  '..oDDDDDDDBBBBBBBBBBBBBBo.....',
  '..oDDDo.oDDBBBBBBBBBBBBBo.....',
  '..oDDo..oDDBWWWWWWWWWWBBo.....',
  '..oDo...oDBWWWWWWWWWWWWBo.....',
  '..oo....oBWWWWWWWWWWWWWBo.....',
  '........oBBBoooooooWWWWBo.....',
  '.......oBBBo.....oBBBBBBo.....',
  '......oBWWo......oBWWoBBBo....',
  '......owwo.......owwo.oWWo....',
  '......ooo.........oo..owwo....',
  '......................ooo.....',
  '..............................',
  '..............................',
];

/** Side profile facing right, legs gathered under the body. Walk key 2. */
export const SIDE_B = [
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '....................oo...oo...',
  '...................oyBo.oByo..',
  '..................oyyBBooBByo.',
  '.................oyBBBBBBBByo.',
  '.................oLLLLLLLLLLo.',
  '................oBBBBBBBBBBBo.',
  '................oBGGGGBBBBBBo.',
  '................oBGSPGBBBnnBo.',
  '................oBGGGGBBBmmBo.',
  '.................oBBBBBBBWWo..',
  '..........ooooooLLLLLLLLLLo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '...ooDDDDDDBBBBBBBBBBBBBo.....',
  '..oDDDDDDDBBBBBBBBBBBBBBo.....',
  '..oDDDo.oDDBBBBBBBBBBBBBo.....',
  '..oDDo..oDDBWWWWWWWWWWBBo.....',
  '..oDo...oDBWWWWWWWWWWWWBo.....',
  '..oo....oBWWWWWWWWWWWWWBo.....',
  '........oBBBBoooooWWWWWBo.....',
  '.........oBBBo...oBBBBBo......',
  '.........oBWWo...oBWWWo.......',
  '.........owwo....owwwo........',
  '.........ooo.....oooo.........',
  '..............................',
  '..............................',
];

/** Side profile facing right, rear legs driving forward. Walk key 3. */
export const SIDE_C = [
  '..............................',
  '..............................',
  '..............................',
  '....................oo...oo...',
  '...................oyBo.oByo..',
  '..................oyyBBooBByo.',
  '.................oyBBBBBBBByo.',
  '.................oLLLLLLLLLLo.',
  '................oBBBBBBBBBBBo.',
  '................oBGGGGBBBBBBo.',
  '................oBGSPGBBBnnBo.',
  '................oBGGGGBBBmmBo.',
  '.................oBBBBBBBWWo..',
  '..........ooooooLLLLLLLLLLo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '...ooDDDDDDBBBBBBBBBBBBBo.....',
  '..oDDDDDDDBBBBBBBBBBBBBBo.....',
  '..oDDDo.oDDBBBBBBBBBBBBBo.....',
  '..oDDo..oDDBWWWWWWWWWWBBo.....',
  '..oDo...oDBWWWWWWWWWWWWBo.....',
  '..oo....oBWWWWWWWWWWWWWBo.....',
  '.......oBBBBoooooooWWWWBo.....',
  '......oBBBBBo....oBBBoBBo.....',
  '.....oBWWWBo.....oWWo.oBo.....',
  '.....owwwo........oo..oWo.....',
  '.....oooo.............owo.....',
  '......................ooo.....',
  '..............................',
  '..............................',
];

/** Side profile facing right, mid-stride suspension. Walk key 4. */
export const SIDE_D = [
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '....................oo...oo...',
  '...................oyBo.oByo..',
  '..................oyyBBooBByo.',
  '.................oyBBBBBBBByo.',
  '.................oLLLLLLLLLLo.',
  '................oBBBBBBBBBBBo.',
  '................oBGGGGBBBBBBo.',
  '................oBGSPGBBBnnBo.',
  '................oBGGGGBBBmmBo.',
  '.................oBBBBBBBWWo..',
  '..........ooooooLLLLLLLLLLo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '...ooDDDDDDBBBBBBBBBBBBBo.....',
  '..oDDDDDDDBBBBBBBBBBBBBBo.....',
  '..oDDDo.oDDBBBBBBBBBBBBBo.....',
  '..oDDo..oDDBWWWWWWWWWWBBo.....',
  '..oDo...oDBWWWWWWWWWWWWBo.....',
  '..oo....oBWWWWWWWWWWWWWBo.....',
  '........oBBoooooooBBWWWBo.....',
  '.......oBBBo....oBBBBBBBo.....',
  '......oBWWWo....oBBBoWWWo.....',
  '......owwwo.....oWWWoowwo.....',
  '......oooo......owwo..ooo.....',
  '................ooo...........',
  '..............................',
];

/** Seen from behind, walking away. Tail raised above the back, no face. */
export const BACK = [
  '..............................',
  '..............................',
  '.......................oo.....',
  '......................oDDo....',
  '......................oDDo....',
  '........oo..........oooDDo....',
  '.......oBBo........oBBoDDo....',
  '......oBBBBo......oBBBoDo.....',
  '......oBBBBoooooooooBBBoo.....',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '.....oBBBBBBBBBBBBBBBBBBo.....',
  '......oBBBBBBBBBBBBBBBBo......',
  '.......oBBBBBBBBBBBBBBo.......',
  '......oLBBBBBBBBBBBBBBLo......',
  '......oBBBBBBBBBBBBBBBBo......',
  '......oBBBBBBBBBBBBBBBBo......',
  '......oBBBBBBBBBBBBBBBBo......',
  '......oBBBBBBBBBBBBBBBBo......',
  '......oBBBBBBBBBBBBBBBBo......',
  '......oBDDBBBBBBBBBBDDBo......',
  '.......oBBBoooooooBBBBo.......',
  '.......oWWWo.....oWWWWo.......',
  '.......oWWWo.....oWWWWo.......',
  '.......owwo.......owwwo.......',
  '.......ooo.........oooo.......',
  '..............................',
  '..............................',
];

/** Leaning in over an edge with wide eyes, watching the user. */
export const PEEK = [
  '..............................',
  '..............................',
  '..............................',
  '..........oo..........oo......',
  '.........oyBo........oByo.....',
  '........oyyBBo......oBByyo....',
  '........oyBBBooooooooBBByo....',
  '.......oLLLLLLLLLLLLLLLLLLo...',
  '......oBBBBBBBBBBBBBBBBBBBBo..',
  '......oBBGGGGGBBBBGGGGGBBBBo..',
  '......oBBGSPPGBBBBGSPPGBBBBo..',
  '......oBBGPPPGBBBBGPPPGBBBBo..',
  '......oBBGGGGGBBBBGGGGGBBBBo..',
  '......oBBBBBBBBnnBBBBBBBBBBo..',
  '......oBBBBBBBWWmmWWBBBBBBBo..',
  '.......oBBBBBBWWWWWWBBBBBBo...',
  '........oBBBBBBWWWWBBBBBBo....',
  '.........oBBBBBBBBBBBBBBo.....',
  '........oLBBBBBWWWWBBBBBLo....',
  '........oBBBBBWWWWWWBBBBBo....',
  '........oWWo.BWWWWWWB.oWWo....',
  '........owwo.BBWWWWBB.owwo....',
  '.........ooooooooooooooooo....',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
];

/** Crouched low, gathering for a jump. */
export const CROUCH = [
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '........oo..........oo........',
  '.......oyBo........oByo.......',
  '......oyyBBo......oBByyo......',
  '......oyBBBooooooooBBByo......',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBGGGGBBBBBBGGGGBBBo....',
  '....oBBBGSPGBBBBBBGSPGBBBo....',
  '....oBBBGGGGBBBBBBGGGGBBBo....',
  '....oBBBBBBBBBnnBBBBBBBBBo....',
  '....oBBBBBBBWWmmWWBBBBBBBo....',
  '.....oBBBBBBWWWWWWBBBBBBo.....',
  '......oBBBBBBBBBBBBBBBBo......',
  '.....oLBBBBBBWWWWBBBBBBLo.....',
  '....oBBBBBBBWWWWWWBBBBBBBo.oo.',
  '....oBBBBBBBWWWWWWBBBBBBBooDDo',
  '....oBBBBBBBBWWWWBBBBBBBBoDDo.',
  '....oBBBBBBBBBBBBBBBBBBBBoDo..',
  '....oBBBBBBBBBBBBBBBBBBBBoo...',
  '....oWWWWoooooooooooWWWWWo....',
  '....oWWWWo.........oWWWWWo....',
  '....owwwwo.........owwwwwo....',
  '....ooooo...........ooooo.....',
  '..............................',
  '..............................',
];

/** Stretched upward at the top of a jump, legs tucked. */
export const STRETCH = [
  '..............................',
  '........oo..........oo........',
  '.......oyBo........oByo.......',
  '......oyyBBo......oBByyo......',
  '......oyBBBooooooooBBByo......',
  '.....oLLLLLLLLLLLLLLLLLLo.....',
  '....oBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBooBBBBBBBBooBBBBo....',
  '....oBBBoBBoBBBBBBoBBoBBBo....',
  '....oBBBBBBBBBnnBBBBBBBBBo....',
  '....oBBBBBBBWWmmWWBBBBBBBo....',
  '.....oBBBBBBWWWWWWBBBBBBo.....',
  '......oBBBBBBWWWWBBBBBBo......',
  '.......oBBBBBBBBBBBBBBo.......',
  '.......oLBBBBWWWWBBBBLo.......',
  '.......oBBBBWWWWWWBBBBo.......',
  '.......oBBBBWWWWWWBBBBo...oo..',
  '.......oBBBBWWWWWWBBBBo..oDDo.',
  '.......oBBBBWWWWWWBBBBo.oDDo..',
  '.......oBBBBWWWWWWBBBBooDDo...',
  '.......oBBBBBWWWWBBBBBoDDo....',
  '.......oBBBBBBBBBBBBBBoDo.....',
  '........oBBBBBBBBBBBBoo.......',
  '........oBBBBBBBBBBBBo........',
  '........oWWWoooooWWWWo........',
  '.........oWWo...oWWWo.........',
  '.........owwo...owwwo.........',
  '.........ooo....oooo..........',
  '..............................',
  '..............................',
];

/** The complete cat pose set, consumed by `buildClips`. */
export const CAT_POSES: PoseSet = {
  front: FRONT,
  frontBlink: FRONT_BLINK,
  frontHappy: FRONT_HAPPY,
  sideA: SIDE_A,
  sideB: SIDE_B,
  sideC: SIDE_C,
  sideD: SIDE_D,
  back: BACK,
  peek: PEEK,
  crouch: CROUCH,
  stretch: STRETCH,
};
