import type { PoseSet } from './build-clips.js';

/**
 * French bulldog sprite art, authored as character grids.
 *
 * Legend matches `cat-art.ts`. The silhouette differs from the cat on purpose:
 * upright bat ears, a wide flat muzzle, a stocky barrel body and a stubby tail,
 * so the two species stay distinguishable at 30px.
 */

/** Sitting, facing the viewer. The resting pose. */
export const FRONT = [
  '..............................',
  '..............................',
  '.....oo................oo.....',
  '....oyyo..............oyyo....',
  '....oyyBo............oByyo....',
  '....oyyBBo..........oBByyo....',
  '....oyyBBBoooooooooBBByyo.....',
  '....oyBBBBBBBBBBBBBBBBByo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBGGGGBBBBBBBBBBGGGGBo....',
  '...oBBGSPGBBBBBBBBBBGSPGBo....',
  '...oBBGGGGBBBBBBBBBBGGGGBo....',
  '...oBBBBBBWWWWWWWWWWBBBBBo....',
  '...oBBBBBWWWWnnWWWWWWBBBBo....',
  '....oBBBBWWWWnnWWWWWWBBBo.....',
  '....oBBBBBWWWmmmmWWWWBBBo.....',
  '.....oBBBBBWWWWWWWWWBBBo......',
  '......oBBBBBBBBBBBBBBo........',
  '.....oLBBBBWWWWWWBBBBLo.......',
  '.....oBBBBWWWWWWWWBBBBo..oo...',
  '.....oBBBBWWWWWWWWBBBBo.oDDo..',
  '.....oBBBBWWWWWWWWBBBBooDDo...',
  '.....oBBBBBWWWWWWBBBBBBoo.....',
  '.....oBBBBBBBBBBBBBBBBo.......',
  '.....oVVVVoooooooWWWWo........',
  '.....oVVVVo.....oWWWWo........',
  '.....ovvvo.......owwwo........',
  '.....oooo.........oooo........',
  '..............................',
];

/** Front pose with the eyes closed, used for the idle blink. */
export const FRONT_BLINK = [
  '..............................',
  '..............................',
  '.....oo................oo.....',
  '....oyyo..............oyyo....',
  '....oyyBo............oByyo....',
  '....oyyBBo..........oBByyo....',
  '....oyyBBBoooooooooBBByyo.....',
  '....oyBBBBBBBBBBBBBBBBByo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBooooBBBBBBBBBBooooBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBWWWWWWWWWWBBBBBo....',
  '...oBBBBBWWWWnnWWWWWWBBBBo....',
  '....oBBBBWWWWnnWWWWWWBBBo.....',
  '....oBBBBBWWWmmmmWWWWBBBo.....',
  '.....oBBBBBWWWWWWWWWBBBo......',
  '......oBBBBBBBBBBBBBBo........',
  '.....oLBBBBWWWWWWBBBBLo.......',
  '.....oBBBBWWWWWWWWBBBBo..oo...',
  '.....oBBBBWWWWWWWWBBBBo.oDDo..',
  '.....oBBBBWWWWWWWWBBBBooDDo...',
  '.....oBBBBBWWWWWWBBBBBBoo.....',
  '.....oBBBBBBBBBBBBBBBBo.......',
  '.....oVVVVoooooooWWWWo........',
  '.....oVVVVo.....oWWWWo........',
  '.....ovvvo.......owwwo........',
  '.....oooo.........oooo........',
  '..............................',
];

/** Front pose grinning with its tongue out, for the heart clip. */
export const FRONT_HAPPY = [
  '..............................',
  '..............................',
  '.....oo................oo.....',
  '....oyyo..............oyyo....',
  '....oyyBo............oByyo....',
  '....oyyBBo..........oBByyo....',
  '....oyyBBBoooooooooBBByyo.....',
  '....oyBBBBBBBBBBBBBBBBByo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBooBBBBBBBBBBBBooBBo....',
  '...oBBoBBoBBBBBBBBBBoBBoBo....',
  '...onnBBBBBBBBBBBBBBBBnnBo....',
  '...onnBBBBWWWWWWWWWWBBnnBo....',
  '...oBBBBBWWWWnnWWWWWWBBBBo....',
  '....oBBBBWWWWnnWWWWWWBBBo.....',
  '....oBBBBBWWWmmmmWWWWBBBo.....',
  '.....oBBBBBWWmmmmmWWBBBo......',
  '......oBBBBBBmmmmBBBBBo.......',
  '.....oLBBBBWWWWWWBBBBLo.......',
  '.....oBBBBWWWWWWWWBBBBo..oo...',
  '.....oBBBBWWWWWWWWBBBBo.oDDo..',
  '.....oBBBBWWWWWWWWBBBBooDDo...',
  '.....oBBBBBWWWWWWBBBBBBoo.....',
  '.....oBBBBBBBBBBBBBBBBo.......',
  '.....oVVVVoooooooWWWWo........',
  '.....oVVVVo.....oWWWWo........',
  '.....ovvvo.......owwwo........',
  '.....oooo.........oooo........',
  '..............................',
];

/** Side profile facing right, front legs reaching forward. Walk key 1. */
export const SIDE_A = [
  '..............................',
  '..............................',
  '..................oo.....oo...',
  '.................oyyo...oyyo..',
  '.................oyyBo.oByyo..',
  '.................oyyBBoBByyo..',
  '.................oyBBBBBBByo..',
  '.................oLLLLLLLLLo..',
  '................oBBBBBBBBBBo..',
  '................oBGGGGBBBBBo..',
  '................oBGSPGBBWWBo..',
  '................oBGGGGBWnnWo..',
  '.................oBBBBBWmmWo..',
  '..........oooooooBBBBBBWWWo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '....oDDDDDDBBBBBBBBBBBBBBo....',
  '...oDDDDDoDBBBBBBBBBBBBBo.....',
  '...oDDDo.oDDBBBBBBBBBBBBo.....',
  '....ooo..oDDBWWWWWWWWWBBo.....',
  '.........oDBWWWWWWWWWWWBo.....',
  '.........oBWWWWWWWWWWWWBo.....',
  '.........oBBBoooooooWWWBo.....',
  '........oBBBo.....oBBBBBo.....',
  '.......oBWWo......oBWWoBBo....',
  '.......owwo.......owwo.oWWo...',
  '.......ooo.........oo..owwo...',
  '.......................ooo....',
  '..............................',
  '..............................',
];

/** Side profile facing right, legs gathered under the body. Walk key 2. */
export const SIDE_B = [
  '..............................',
  '..............................',
  '..............................',
  '..................oo.....oo...',
  '.................oyyo...oyyo..',
  '.................oyyBo.oByyo..',
  '.................oyyBBoBByyo..',
  '.................oyBBBBBBByo..',
  '.................oLLLLLLLLLo..',
  '................oBBBBBBBBBBo..',
  '................oBGGGGBBBBBo..',
  '................oBGSPGBBWWBo..',
  '................oBGGGGBWnnWo..',
  '.................oBBBBBWmmWo..',
  '..........oooooooBBBBBBWWWo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '....oDDDDDDBBBBBBBBBBBBBBo....',
  '...oDDDDDoDBBBBBBBBBBBBBo.....',
  '...oDDDo.oDDBBBBBBBBBBBBo.....',
  '....ooo..oDDBWWWWWWWWWBBo.....',
  '.........oDBWWWWWWWWWWWBo.....',
  '.........oBWWWWWWWWWWWWBo.....',
  '.........oBBBBoooooWWWWBo.....',
  '..........oBBBo...oBBBBo......',
  '..........oBWWo...oBWWWo......',
  '..........owwo....owwwo.......',
  '..........ooo.....oooo........',
  '..............................',
  '..............................',
];

/** Side profile facing right, rear legs driving forward. Walk key 3. */
export const SIDE_C = [
  '..............................',
  '..............................',
  '..................oo.....oo...',
  '.................oyyo...oyyo..',
  '.................oyyBo.oByyo..',
  '.................oyyBBoBByyo..',
  '.................oyBBBBBBByo..',
  '.................oLLLLLLLLLo..',
  '................oBBBBBBBBBBo..',
  '................oBGGGGBBBBBo..',
  '................oBGSPGBBWWBo..',
  '................oBGGGGBWnnWo..',
  '.................oBBBBBWmmWo..',
  '..........oooooooBBBBBBWWWo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '....oDDDDDDBBBBBBBBBBBBBBo....',
  '...oDDDDDoDBBBBBBBBBBBBBo.....',
  '...oDDDo.oDDBBBBBBBBBBBBo.....',
  '....ooo..oDDBWWWWWWWWWBBo.....',
  '.........oDBWWWWWWWWWWWBo.....',
  '.........oBWWWWWWWWWWWWBo.....',
  '........oBBBBoooooooWWWBo.....',
  '.......oBBBBBo....oBBBoBo.....',
  '......oBWWWBo.....oWWo.oBo....',
  '......owwwo........oo..oWo....',
  '......oooo.............owo....',
  '.......................ooo....',
  '..............................',
  '..............................',
];

/** Side profile facing right, mid-stride suspension. Walk key 4. */
export const SIDE_D = [
  '..............................',
  '..............................',
  '..............................',
  '..................oo.....oo...',
  '.................oyyo...oyyo..',
  '.................oyyBo.oByyo..',
  '.................oyyBBoBByyo..',
  '.................oyBBBBBBByo..',
  '.................oLLLLLLLLLo..',
  '................oBBBBBBBBBBo..',
  '................oBGGGGBBBBBo..',
  '................oBGSPGBBWWBo..',
  '................oBGGGGBWnnWo..',
  '.................oBBBBBWmmWo..',
  '..........oooooooBBBBBBWWWo...',
  '.......oooDDDBBBBBBBBBBBBo....',
  '.....ooDDDDDBBBBBBBBBBBBBo....',
  '....oDDDDDDBBBBBBBBBBBBBBo....',
  '...oDDDDDoDBBBBBBBBBBBBBo.....',
  '...oDDDo.oDDBBBBBBBBBBBBo.....',
  '....ooo..oDDBWWWWWWWWWBBo.....',
  '.........oDBWWWWWWWWWWWBo.....',
  '.........oBWWWWWWWWWWWWBo.....',
  '.........oBBoooooooBWWWBo.....',
  '........oBBBo....oBBBBBBo.....',
  '.......oBWWWo....oBBBoWWo.....',
  '.......owwwo.....oWWWoowwo....',
  '.......oooo......owwo..ooo....',
  '.................ooo..........',
  '..............................',
];

/** Seen from behind, walking away. Stubby tail, no face. */
export const BACK = [
  '..............................',
  '..............................',
  '.....oo................oo.....',
  '....oBBo..............oBBo....',
  '....oBBBo............oBBBo....',
  '....oBBBBo..........oBBBBo....',
  '....oBBBBBoooooooooBBBBBo.....',
  '....oBBBBBBBBBBBBBBBBBBBo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '....oBBBBBBBBBBBBBBBBBBBo.....',
  '.....oBBBBBBBBBBBBBBBBBo......',
  '......oBBBBBBBBBBBBBBBo.......',
  '.............oDDo.............',
  '.....oLBBBBBBoDDoBBBBBLo......',
  '.....oBBBBBBBoooBBBBBBBo......',
  '.....oBBBBBBBBBBBBBBBBBo......',
  '.....oBBBBBBBBBBBBBBBBBo......',
  '.....oBBBBBBBBBBBBBBBBBo......',
  '.....oBDDBBBBBBBBBBBDDBo......',
  '.....oBBBBBBBBBBBBBBBBBo......',
  '.....oBBBBoooooooBBBBBBo......',
  '.....oVVVVo.....oWWWWWo.......',
  '.....oVVVVo.....oWWWWWo.......',
  '.....ovvvo.......owwwwo.......',
  '.....oooo.........ooooo.......',
  '..............................',
];

/** Leaning in over an edge with wide eyes, watching the user. */
export const PEEK = [
  '..............................',
  '..............................',
  '.......oo................oo...',
  '......oyyo..............oyyo..',
  '......oyyBo............oByyo..',
  '......oyyBBo..........oBByyo..',
  '......oyyBBBoooooooooBBByyo...',
  '......oyBBBBBBBBBBBBBBBBByo...',
  '......oLLLLLLLLLLLLLLLLLLLo...',
  '.....oBBBBBBBBBBBBBBBBBBBBBo..',
  '.....oBBGGGGGBBBBBBBBGGGGGBo..',
  '.....oBBGSPPGBBBBBBBBGSPPGBo..',
  '.....oBBGPPPGBBBBBBBBGPPPGBo..',
  '.....oBBGGGGGBBBBBBBBGGGGGBo..',
  '.....oBBBBBBWWWWWWWWWWBBBBBo..',
  '.....oBBBBBWWWWnnWWWWWWBBBBo..',
  '......oBBBBWWWWnnWWWWWWBBBo...',
  '......oBBBBBWWWmmmmWWWWBBBo...',
  '.......oBBBBBWWWWWWWWWBBBo....',
  '........oBBBBBBBBBBBBBBo......',
  '.......oLBBBBWWWWWWBBBBLo.....',
  '.......oVVo.BWWWWWWWWB.oWWo...',
  '.......ovvo.BBWWWWWWBB.owwo...',
  '........ooooooooooooooooooo...',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
];

/** Crouched low, gathering for a jump. */
export const CROUCH = [
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '.....oo................oo.....',
  '....oyyo..............oyyo....',
  '....oyyBo............oByyo....',
  '....oyyBBo..........oBByyo....',
  '....oyyBBBoooooooooBBByyo.....',
  '....oyBBBBBBBBBBBBBBBBByo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBGGGGBBBBBBBBBBGGGGBo....',
  '...oBBGSPGBBBBBBBBBBGSPGBo....',
  '...oBBGGGGBBBBBBBBBBGGGGBo....',
  '...oBBBBBBWWWWWWWWWWBBBBBo....',
  '...oBBBBBWWWWnnWWWWWWBBBBo....',
  '....oBBBBWWWWnnWWWWWWBBBo.....',
  '....oBBBBBWWWmmmmWWWWBBBo.....',
  '....oBBBBBBBBBBBBBBBBBBBo.oo..',
  '...oLBBBBBWWWWWWWWWBBBBBLooDDo',
  '...oBBBBBWWWWWWWWWWWBBBBBooDDo',
  '...oBBBBBWWWWWWWWWWWBBBBBBoo..',
  '...oBBBBBBWWWWWWWWWBBBBBBBo...',
  '...oBBBBBBBBBBBBBBBBBBBBBBo...',
  '...oVVVVVoooooooooooWWWWWWo...',
  '...oVVVVVo.........oWWWWWWo...',
  '...ovvvvo...........owwwwwo...',
  '...ooooo.............oooooo...',
  '..............................',
];

/** Stretched upward at the top of a jump, legs tucked. */
export const STRETCH = [
  '..............................',
  '.....oo................oo.....',
  '....oyyo..............oyyo....',
  '....oyyBo............oByyo....',
  '....oyyBBo..........oBByyo....',
  '....oyyBBBoooooooooBBByyo.....',
  '....oyBBBBBBBBBBBBBBBBByo.....',
  '....oLLLLLLLLLLLLLLLLLLLo.....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBooBBBBBBBBBBBBooBBo....',
  '...oBBoBBoBBBBBBBBBBoBBoBo....',
  '...oBBBBBBBBBBBBBBBBBBBBBo....',
  '...oBBBBBBWWWWWWWWWWBBBBBo....',
  '...oBBBBBWWWWnnWWWWWWBBBBo....',
  '....oBBBBWWWWnnWWWWWWBBBo.....',
  '....oBBBBBWWWmmmmWWWWBBBo.....',
  '.....oBBBBBWWWWWWWWWBBBo......',
  '......oBBBBBBBBBBBBBBo........',
  '......oLBBBWWWWWWWWBBLo...oo..',
  '......oBBBWWWWWWWWWWBBo..oDDo.',
  '......oBBBWWWWWWWWWWBBo.oDDo..',
  '......oBBBWWWWWWWWWWBBooDDo...',
  '......oBBBBWWWWWWWWBBBBoDo....',
  '......oBBBBBBBBBBBBBBBBoo.....',
  '.......oBBBBBBBBBBBBBBo.......',
  '.......oVVVVoooooWWWWWo.......',
  '........oVVo.....oWWWo........',
  '........ovvo.....owwwo........',
  '........ooo.......oooo........',
  '..............................',
];

/** The complete French bulldog pose set, consumed by `buildClips`. */
export const DOG_POSES: PoseSet = {
  front: FRONT,
  frontBlink: FRONT_BLINK,
  frontHappy: FRONT_HAPPY,
  sideA: SIDE_A,
  sideB: SIDE_B,
  sideC: SIDE_C,
  sideD: SIDE_D,
  back: BACK,
  peek: PEEK,
  crouch: CROUCH,
  stretch: STRETCH,
};
